//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GopherDirtBikeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int ComponentID { get; set; }
        public string Fork { get; set; }
        public string Drivetrain { get; set; }
        public string RearSuspension { get; set; }
        public string WheelSize { get; set; }
    
        public virtual Bike Bike { get; set; }
    }
}
